### ISSUE TITLE
原件初始值以及更新值

### ISSUE THREAD

**Issue by groupystinks** [react-component/m-cascader#15]
Hi 各位,
感謝react-component跟antd的開發，非常好用。

## Issue 回報
[demo](https://codesandbox.io/s/x3w67v22rw)

1. 當原件初始值為2時，打開Cascader發現選取的值仍然為1。
2. 當點擊“點我更新value到3”後，打開Cascader發現選取的值並沒有更新為3。

## 可能解法
[原碼](https://github.com/react-component/m-cascader/blob/master/src/Cascader.tsx#L56)
getValue在取值時，會先重置使用者傳入的value，接下來默認data的第一項為初始值。可以在getValue中，考慮使用者傳入的value來解決。

我很樂意提供PR。

**Comment by warmhug** [comment]
你 demo 写法有问题，看这个 https://codesandbox.io/s/6vl543l61n 没问题

**Comment by groupystinks** [comment]
ok，謝謝修正。
